# Generated by Django 2.2 on 2019-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190414_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='so', max_length=256),
            preserve_default=False,
        ),
    ]
