# Generated by Django 2.2 on 2019-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='content_ar',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='content_fr',
            field=models.CharField(default='yy', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='description_fr',
            field=models.CharField(default='yy', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='description_fr',
            field=models.CharField(default='yy', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_ar',
            field=models.CharField(default='yy', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_fr',
            field=models.CharField(default='yy', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='name_ar',
            field=models.CharField(default='tt', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='name_fr',
            field=models.CharField(default='uu', max_length=128),
            preserve_default=False,
        ),
    ]
